/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppNavber: typeof import('./components/app/AppNavber.vue')['default']
    Chat: typeof import('./components/dashboard/Chat.vue')['default']
    Keywords: typeof import('./components/dashboard/Keywords.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhisperGoGo: typeof import('./components/dashboard/WhisperGoGo.vue')['default']
  }
}
