// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BringToFront() {
  return window['go']['main']['App']['BringToFront']();
}

export function GetDeviceName() {
  return window['go']['main']['App']['GetDeviceName']();
}

export function GetKeywords() {
  return window['go']['main']['App']['GetKeywords']();
}

export function GetNtfyTopics() {
  return window['go']['main']['App']['GetNtfyTopics']();
}

export function ResetNtfyTopics() {
  return window['go']['main']['App']['ResetNtfyTopics']();
}

export function SetKeywords(arg1) {
  return window['go']['main']['App']['SetKeywords'](arg1);
}

export function SetNtfyTopics(arg1) {
  return window['go']['main']['App']['SetNtfyTopics'](arg1);
}
