// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BringToFront():Promise<void>;

export function GetAlertStatus():Promise<boolean>;

export function GetAlertType():Promise<main.AlertType>;

export function GetChatFilters():Promise<Array<main.ChatType>>;

export function GetGameStatus():Promise<boolean>;

export function GetKeywords():Promise<Array<main.Keyword>>;

export function GetTelegramChatID():Promise<string>;

export function ResetKeywords():Promise<void>;

export function SetAlertStatus(arg1:boolean):Promise<void>;

export function SetAlertType(arg1:main.AlertType):Promise<void>;

export function SetChatFilters(arg1:Array<main.ChatType>):Promise<void>;

export function SetKeywords(arg1:Array<main.Keyword>):Promise<void>;

export function SetTelegramChatID(arg1:string):Promise<main.VerifyChatResponse>;
