// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BringToFront() {
  return window['go']['main']['App']['BringToFront']();
}

export function GetAlertStatus() {
  return window['go']['main']['App']['GetAlertStatus']();
}

export function GetAlertType() {
  return window['go']['main']['App']['GetAlertType']();
}

export function GetChatFilters() {
  return window['go']['main']['App']['GetChatFilters']();
}

export function GetGameStatus() {
  return window['go']['main']['App']['GetGameStatus']();
}

export function GetKeywords() {
  return window['go']['main']['App']['GetKeywords']();
}

export function GetTelegramChatID() {
  return window['go']['main']['App']['GetTelegramChatID']();
}

export function OpenTelegramLink() {
  return window['go']['main']['App']['OpenTelegramLink']();
}

export function ResetKeywords() {
  return window['go']['main']['App']['ResetKeywords']();
}

export function SetAlertStatus(arg1) {
  return window['go']['main']['App']['SetAlertStatus'](arg1);
}

export function SetAlertType(arg1) {
  return window['go']['main']['App']['SetAlertType'](arg1);
}

export function SetChatFilters(arg1) {
  return window['go']['main']['App']['SetChatFilters'](arg1);
}

export function SetKeywords(arg1) {
  return window['go']['main']['App']['SetKeywords'](arg1);
}

export function SetTelegramChatID(arg1) {
  return window['go']['main']['App']['SetTelegramChatID'](arg1);
}
